## site registration
POST http://localhost:8083/shortcut/registration/
Content-Type: application/json

{
  "domainUrl": "job4j.ru"
}

###

## get JWT for login&password
POST http://localhost:8083/shortcut/login/
Content-Type: application/json

{
  "login": "asdf",
  "password": "1234"
}

###

## encode url
POST http://localhost:8083/shortcut/urls/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhc2RmIiwiZXhwIjoxNjE3MTI1NzE3LCJpYXQiOjE2MTcxMDc3MTd9.iZcF9-yNEr3_5jR9LeGNyU1lm0JCd1znAS3s0elcFST2oRcFrvbF5jKlS-xMh2Zn-KXsciA-pK4pO61F4iXiAg

{
  "url": "job4j.ru/edu"
}

###

## decode url
## "urlKey": "UNIQUE_CODE" - change every runtime.
GET http://localhost:8083/shortcut/urls/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhc2RmIiwiZXhwIjoxNjE3MTI1NzE3LCJpYXQiOjE2MTcxMDc3MTd9.iZcF9-yNEr3_5jR9LeGNyU1lm0JCd1znAS3s0elcFST2oRcFrvbF5jKlS-xMh2Zn-KXsciA-pK4pO61F4iXiAg

{
  "urlKey": "0iKQDhSdcRjpUQDpk8yYl29lFc9wQmPQ"
}

###

## redirect url
## "urlKey": "UNIQUE_CODE" - change every runtime.
GET http://localhost:8083/shortcut/urls/redirect
Content-Type: application/json

{
  "urlKey": "0iKQDhSdcRjpUQDpk8yYl29lFc9wQmPQ"
}

###

## get statistic
GET http://localhost:8083/shortcut/urls/statistic
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhc2RmIiwiZXhwIjoxNjE3MTI1NzE3LCJpYXQiOjE2MTcxMDc3MTd9.iZcF9-yNEr3_5jR9LeGNyU1lm0JCd1znAS3s0elcFST2oRcFrvbF5jKlS-xMh2Zn-KXsciA-pK4pO61F4iXiAg


###