## site registration
POST http://localhost:8083/shortcut/registration/
Content-Type: application/json

{
  "domainUrl": "job4j.ru"
}

###

## get JWT for login&password
POST http://localhost:8083/shortcut/login/
Content-Type: application/json

{
  "login": "asdf",
  "password": "1234"
}

###

## encode url
POST http://localhost:8083/shortcut/urls/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhc2RmIiwiZXhwIjoxNjE2NDUyNjQ4LCJpYXQiOjE2MTY0MzQ2NDh9.CEQIag_sIFLnyYWfr-3iQMsB8QnGZOulhoj_X0hGA4a8Qglc2HBzo1BowQtLuq250WteLoiBMYw2qOGwf--xwA

{
  "url": "job4j.ru/edu"
}

###

## decode url
## "urlKey": "UNIQUE_CODE" - change every runtime.
GET http://localhost:8083/shortcut/urls/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhc2RmIiwiZXhwIjoxNjE2NDUyNjQ4LCJpYXQiOjE2MTY0MzQ2NDh9.CEQIag_sIFLnyYWfr-3iQMsB8QnGZOulhoj_X0hGA4a8Qglc2HBzo1BowQtLuq250WteLoiBMYw2qOGwf--xwA

{
  "urlKey": "l9ZNVKOiWjimiABtTL059ocwaO0GcMlh"
}

###

## redirect url
## "urlKey": "UNIQUE_CODE" - change every runtime.
GET http://localhost:8083/shortcut/urls/redirect
Content-Type: application/json

{
  "urlKey": "l9ZNVKOiWjimiABtTL059ocwaO0GcMlh"
}

###

## get statistic
GET http://localhost:8083/shortcut/urls/statistic
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhc2RmIiwiZXhwIjoxNjE2NDUyNjQ4LCJpYXQiOjE2MTY0MzQ2NDh9.CEQIag_sIFLnyYWfr-3iQMsB8QnGZOulhoj_X0hGA4a8Qglc2HBzo1BowQtLuq250WteLoiBMYw2qOGwf--xwA


###